services:
  pg_database:
    networks:
      - pg-network
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
  
  pgadmin:
    image: dpage/pgadmin4
    networks:
      - pg-network
    container_name: pg_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80

  taxi_ingest:
    image: taxi_ingest:v01
    build: .
    # parse argument into python file when running in docker container
    command: ["--user", "root",
     "--password", "root",
     "--host", "postgres_db",
     "--port" , "5432",
     "--database", "ny_taxi",
     "--table", "yellow_ny_data",
     "--url" ,"https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet"]
    container_name: taxi_ingest_container
    networks:
      - pg-network

networks:
  pg-network:
    name: pg-network
    driver: bridge